controllers/ResumesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Resumes;
use app\models\ResumesSearch;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\filters\AccessControl;

/**
 * ResumesController implements the CRUD actions for Resumes model.
 */
class ResumesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'update', 'delete'],
                'rules' => [
                    [
                        'actions' => ['index', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Resumes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ResumesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Resumes model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Resumes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Resumes();
        $this->uploadResumes($model);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }
    protected function uploadResumes(Resumes $model)
    {
        if ($model->load(Yii::$app->request->post())) {
            $model->upload = UploadedFile::getInstance($model, 'upload');

            if ($model->validate()) {
                if ($model->upload) {
                    $filePath = 'uploads/' . $model->upload->baseName . '.' . $model->upload->extension;
                    if ($model->upload->saveAs($filePath)) {
                        $model->resumes = $filePath;
                    }
                }

                if ($model->save(false)) {
                    return $this->redirect(['view', 'id' => $model->id]);
                }
            }
        }
    }

    /**
     * Updates an existing Resumes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Resumes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    public function actionSearch(){
        $request = array_filter(Yii::$app->request->post());
        $searchConditions = null;
        $index = 0;
        foreach ($request as $key=>$value){
            if($index>0){
                $searchConditions.=" "."AND"." ";
                $index = 0;
            }
            $searchConditions .= $key." "."LIKE '%$value%'";
            $index++;
        }
        $result  = Resumes::find()->where($searchConditions)->all();
        if(!empty($result)) {
            return Json::encode($result);
        }
    }

    /**
     * Finds the Resumes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Resumes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Resumes::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

//$this->title = 'About';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <h2> Task description </h2>
    <p>
        The page must give user opportunity to add items(people profiles) and then search among them.</p>
    <h3>Adding</h3>
    <p> The first part is adding. User can add items with following fields. All fields must be filled, not
        empty.<br><br>
        first name _____<br>
        last name _____<br>
        keywords _____ (words describing the person, e.g. html, ysu, 19, etc.)<br>
        resume attach button (file can be upload, extension of uploaded file must be limited to .doc(x), .pdf,
        .txt)<br><br></p>
    <h3>Searching</h3>
    <p>The data entered is sent to MySQL database and then can be searched from there via these fields:<br><br>
        first name _____<br>
        last name _____<br>
        keywords _____<br><br>
        At least one of the fields above must be used, filling all is not necessary. Item is chosen from
        Database and shown in case it or part of it contains searched terms. If more then one field is filled
        during search, only results with both or three field concurrence are shown.
        The search results are shown like this:
    </p>
    <table>
        <tr>
            <th>first name</th>
            <th>last name</th>
            <th>keywords</th>
            <th>resume</th>
        </tr>
        <tr>
            <th>first name of relevant
                item is shown</th>
            <th>last name of relevant
                item is shown</th>
            <th>keywords of relevant
                item are shown</th>
            <th>link (clicking on the
                link opens ''save as''
                window. this part lets
                us to download resume
                we have attached )</th>
        </tr>
    </table>
    <h2>For example.</h2>
    <p>
    I have added the following item besides others:<br>
    first name _armen<br>
    last name _poghosyan<br>
    keywords _ gitc, , phpbeginner, football<br>
    resume – “resume_armen_poghosyan.pdf” file is attached<br>

    After a while, I want to find the item I mentioned, but I remember only part of the information I
    added earlier. So I add in the fields the information I remember and search for it. For example:<br>
    first name _armen<br>
    last name _____ (left empty, i do not remember )<br>
    keywords _php<br><br>
    So the shown result will include discussed item, because “armen” is contained in the first name
    wholly and keyword “php” is included partly (the item had keyword “phpbeginner” which includes
    “php”).<br>
        Other items including searching terms also will be shown.</p>
    <table>
        <tr>
            <th>first name</th>
            <th>last name</th>
            <th>keywords</th>
            <th>resume</th>
        </tr>
        <tr>
            <th>armen</th>
            <th>poghosyan</th>
            <th>gitc, xhtml,
                phpbeginner, football</th>
            <th>link ( downloads “
                resume_armen_poghos
                yan.pdf” )</th>
        </tr>
        <tr>
            <th>armen</th>
            <th>arshakyan</th>
            <th>ysu, css, phpsenior</th>
            <th>link ( downloads “
                resume_armen_arshaky
                an.doc” )</th>
        </tr>
        <tr>
            <th>armenuhi</th>
            <th>sarksyan</th>
            <th>seua, phpmiddle,</th>
            <th>link ( downloads “
                resume_armenuhi_sark
                syan.txt” )</th>
        </tr>
    </table>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Resumes';
?>
<div class="site-index">



    <div class="body-content">
        <div class="row">
            <div class="text-right">
                <a href="<?=Url::to('/resumes/create');?>" class="btn btn-success">Add Resume</a>
            </div>
            <div class="form-group search-form">
                <div class="col-lg-12">
                    <div class="col-md-2">
                        <label for="first-name">First Name</label>
                        <input type="text" id="first-name" class="form-control" name="first_name" placeholder="First Name"/>
                    </div>
                    <div class="col-md-2">
                        <label for="last-name">Last Name</label>
                        <input type="text" id="last-name" class="form-control" name="last_name" placeholder="Last Name"/>
                    </div>
                    <div class="col-md-4">
                        <label for="keywords">Keywords</label>
                        <input type="text" id="keywords" class="form-control" name="keywords" placeholder="Keywords"/>
                    </div>
                    <div class="col-md-3">
                        <label for="resume">Resume</label>
                        <input type="text" id="resume" class="form-control" name="resume" placeholder="Resume"/>
                    </div>
                    <div class="col-md-1 search-button-section">
                        <button type="button" id="search" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>